# Generated by Django 5.1 on 2024-08-23 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_api', '0002_automarkamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='automarkamodel',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='car_api.countrymodel', verbose_name='Страна'),
        ),
    ]
