# Generated by Django 5.1 on 2024-08-23 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_api', '0003_automarkamodel_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoColorDefaultsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=255, verbose_name='Название цвета')),
            ],
            options={
                'verbose_name': 'Цвет авто',
                'verbose_name_plural': 'Цвета авто',
            },
        ),
        migrations.CreateModel(
            name='AutoKPPTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpp_type', models.CharField(max_length=255, verbose_name='Тип КПП')),
            ],
            options={
                'verbose_name': 'Тип КПП',
                'verbose_name_plural': 'Типы КПП',
            },
        ),
        migrations.CreateModel(
            name='AutoPrivDefaultsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priv_name', models.CharField(max_length=255, verbose_name='Вид привода')),
            ],
            options={
                'verbose_name': 'Привод авто',
                'verbose_name_plural': 'Приводы авто',
            },
        ),
        migrations.CreateModel(
            name='AutoWheelTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel_type', models.CharField(max_length=10, verbose_name='Тип руля')),
            ],
            options={
                'verbose_name': 'Тип руля',
                'verbose_name_plural': 'Типы руля',
            },
        ),
        migrations.CreateModel(
            name='AutoYearDefaultsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год автомобиля')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_api.countrymodel', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Год авто',
                'verbose_name_plural': 'Года авто',
            },
        ),
    ]
